---
- name: clone the beaker repository
  git:
    repo: git://git.beaker-project.org/beaker
    depth: 1
    dest: /tmp/beaker
    accept_hostkey: yes

- name: install yum utility
  sudo: yes
  yum:
    name: yum-utils
    state: present

- name: install dependent beaker packages
  sudo: yes
  command: "yum-builddep -y /tmp/beaker/beaker.spec"

- name: remove temporary cloned beaker repository
  command: "rm -rf /tmp/beaker"

- name: install runtime dependencies
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "beaker-server-testing"
  with_items:
    - firefox
    - nodejs-less
    - openldap-servers
    - python-daemon
    - python-gunicorn
    - python-isodate
    - python-kerberos
    - python-lockfile
    - python-nose-progressive
    - python-rdflib
    - python-requests-kerberos
    - python-tgexpandingformwidget
    - selenium-python
    - uglify-js
    - xorg-x11-server-Xvfb
    - pylint
    - pytest
    - PyXML  # needed by beah and used on Jenkins in dogfood tests
    - xz  # to import database dumps

- name: workaround | delete installed TG version
  sudo: yes
  yum:
    name: "TurboGears"
    state: absent

- name: workaround | prefer custom build TG from beaker server
  sudo: yes
  yum:
    name: "TurboGears-1.1.3-2.el6eng.3.noarch"
    state: present
